//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movy
    {
        public int MId { get; set; }
        public string Mname { get; set; }
        public string Mcategory { get; set; }
        public string Mproducer { get; set; }
        public string Myear { get; set; }
        public Nullable<int> userId { get; set; }
    
        public virtual User User { get; set; }
    }
}
